# ==========================================
# 1. 기본 시스템 설정
# ==========================================
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# ==========================================
# 2. 내부/테스트용 포트 (1883)
# ==========================================
listener 1883
protocol mqtt
allow_anonymous true

# ==========================================
# 3. 보안용 포트 (8883)
# ==========================================
# listener 8883
# protocol mqtt

# 인증서 경로 (컨테이너 내부 기준)
# cafile /mosquitto/config/certs/ca.crt
# certfile /mosquitto/config/certs/server.crt
# keyfile /mosquitto/config/certs/server.key

# TLS 버전
# tls_version tlsv1.2
