spring.config.import=classpath:application-secret.properties

spring.application.name=ddulo
# \uAC1C\uBC1C: dev, \uC6B4\uC601: prod
spring.profiles.active=dev

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# \uC11C\uBC84 \uAE30\uBCF8 \uC124\uC815
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
# \uCF58\uC194 \uB85C\uADF8 \uC0C9\uC0C1 \uC785\uD788\uAE30(\uAC00\uB3C5\uC131)
spring.output.ansi.enabled=always

# JPA / Hibernate \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# camel <-> snake \uBCC0\uD658 \uC124\uC815
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.naming.implicit-strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
# Auditing (BaseTimeEntity) \uC0AC\uC6A9\uC744 \uC704\uD55C \uC124\uC815
spring.jpa.open-in-view=false

# (\uCC38\uACE0) DDL Auto \uC124\uC815 (\uD14C\uC774\uBE14 \uC790\uB3D9 \uC0DD\uC131/\uC5C5\uB370\uC774\uD2B8)
spring.jpa.hibernate.ddl-auto=update

# Spring Boot\uC758 Docker Compose \uC790\uB3D9 \uC2E4\uD589 \uBC29\uC9C0
spring.docker.compose.enabled=false

# \uC678\uBD80 API \uC124\uC815

# SK Open API URL
sk.api.key=${SK_API_APPKEY}
# 1. \uC9C0\uD558\uCCA0 \uC5ED \uBAA9\uB85D
sk.api.url.station=https://apis.openapi.sk.com/puzzle/subway/meta/stations
# 2. \uC5F4\uCC28\u00B7\uCE78 \uD63C\uC7A1\uB3C4(3\uAC1C\uC6D4 \uD1B5\uACC4)
# \uD480\uBC84\uC804: https://apis.openapi.sk.com/puzzle/subway/congestion/stat/car/stations/\uC5ED\uCF54\uB4DC(\uC9C0\uD558\uCCA0 \uC5ED \uBAA9\uB85D api\uC758 stationCode\uAC12)
sk.api.url.subway.congestion=https://apis.openapi.sk.com/puzzle/subway/congestion/stat/car/stations

# \uC11C\uC6B8 \uC5F4\uB9B0 \uB370\uC774\uD130 \uAD11\uC7A5
seoul.api.key=${SEOUL_API_APPKEY}
seoul.api.subway.key=${SEOUL_API_SUBWAY_APPKEY}
# 3. \uC11C\uC6B8\uC2DC \uAD50\uD1B5\uACF5\uC0AC \uC9C0\uD558\uCCA0\uC5ED \uBE60\uB978\uD558\uCC28\uC815\uBCF4 \uD604\uD669(\uBC18\uBCF5\uBB38 1\uD68C\uB2F9 1000\uAC1C \uAC00\uC838\uC624\uAE30 \uAD8C\uC7A5, \uAC00\uC838\uC640\uC57C\uD558\uB294 \uCD1D \uB370\uC774\uD130\uB294 \uC57D 2400\uAC1C)
seoul.api.url.alight=http://openapi.seoul.go.kr:8088/${seoul.api.key}/json/getFstExit
# 4. \uC11C\uC6B8\uC2DC \uAD50\uD1B5\uACF5\uC0AC \uC9C0\uD558\uCCA0\uC5ED \uCD5C\uB2E8\uACBD\uB85C\uC774\uB3D9\uC815\uBCF4 \uD604\uD669
# \uD480\uBC84\uC804: http://openapi.seoul.go.kr:8088/${seoul.api.key}/json/getShtrmPath/1/1/\uC2DC\uC791\uC5ED/\uB3C4\uCC29\uC5ED/\uD604\uC7AC\uC2DC\uAC01
seoul.api.url.shortest=http://openapi.seoul.go.kr:8088/${seoul.api.key}/json/getShtrmPath/1/1
# 5. \uC11C\uC6B8\uC2DC \uC9C0\uD558\uCCA0 \uC2E4\uC2DC\uAC04 \uC5F4\uCC28 \uC704\uCE58\uC815\uBCF4
# \uD480\uBC84\uC804: http://swopenAPI.seoul.go.kr/api/subway/${seoul.api.subway.key}/json/realtimePosition/0/100/\uC5ED\uC774\uB984
seoul.api.url.now=http://swopenAPI.seoul.go.kr/api/subway/${seoul.api.subway.key}/json/realtimePosition/0/100
# 6. \uC11C\uC6B8\uC2DC \uC5ED\uCF54\uB4DC\uB85C \uC9C0\uD558\uCCA0 \uC5F4\uCC28 \uC2DC\uAC04\uD45C \uAC80\uC0C9
# \uD480\uBC84\uC804: http://openAPI.seoul.go.kr:8088/${seoul.api.key}/json/SearchSTNTimeTableByIDService/1(\uD398\uC774\uC9C0\uC2DC\uC791)/5(\uD398\uC774\uC9C0\uB05D)/0309(\uC5ED\uCF54\uB4DC)/1(\uC694\uC77C: 1-\uD3C9\uC77C, 2-\uD1A0\uC694\uC77C, 3-\uACF5\uD734\uC77C&\uC77C\uC694\uC77C)/1(\uC9C4\uD589\uBC29\uD5A5: 1-\uC0C1\uD589/\uB0B4\uC120, 2-\uD558\uD589/\uC678\uC120)
seoul.api.url.timetable=http://openAPI.seoul.go.kr:8088/${seoul.api.key}/json/SearchSTNTimeTableByIDService/1/500

# \uAD6D\uD1A0\uAD50\uD1B5\uBD80 \uACF5\uACF5 \uB370\uC774\uD130 \uD3EC\uD138
data.api.encoding.key=${DATA_API_ENCODING_APPKEY}
data.api.decoding.key=${DATA_API_DECODING_APPKEY}
# 7. \uAD6D\uD1A0\uAD50\uD1B5\uBD80 - \uCCA0\uB3C4\uC5ED \uBE60\uB978 \uD658\uC2B9 \uC815\uBCF4
# \uD480\uBC84\uC804: https://api.odcloud.kr/api/15151816/v1/uddi:e9c2bb71-05e8-4767-8397-9df787ee70f6?page=\uD398\uC774\uC9C0 \uBC88\uD638&perPage=\uD55C \uD398\uC774\uC9C0\uB2F9 \uD589 \uAC1C\uC218&serviceKey=\uC778\uC99D\uD0A4
data.api.url.transfer=https://api.odcloud.kr/api/15151816/v1/uddi:e9c2bb71-05e8-4767-8397-9df787ee70f6

# Python API URL
python.api.url.station=http://localhost:8001/calculate/station
python.api.url.path=http://localhost:8001/calculate/path

# \uBAA8\uB4E0 Actuator \uC5D4\uB4DC\uD3EC\uC778\uD2B8 \uB178\uCD9C (\uAC1C\uBC1C/\uD14C\uC2A4\uD2B8\uC6A9)
management.endpoints.web.exposure.include=*
# \uD5EC\uC2A4 \uCCB4\uD06C \uC2DC \uC0C1\uC138 \uC815\uBCF4(DB \uC5F0\uACB0 \uC0C1\uD0DC, \uB514\uC2A4\uD06C \uACF5\uAC04 \uB4F1) \uD45C\uC2DC
management.endpoint.health.show-details=always
