# \uB85C\uCEEC \uAC1C\uBC1C \uD658\uACBD \uC124\uC815

# MySQL DB \uC124\uC815(docker \uC0AC\uC6A9 \uAC00\uC815)
spring.datasource.url=jdbc:mysql://localhost:3306/ddulo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&profileSQL=false&logger=Slf4JLogger
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

# Redis Configuration (\uCE90\uC2DC/\uBC84\uD37C \uC124\uC815)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PWD}

# ORM \uC124\uC815 (JPA / Hibernate Configuration)
# \uC2A4\uD0A4\uB9C8 \uC790\uB3D9 \uC0DD\uC131 (\uAC1C\uBC1C \uC2DC update, \uC6B4\uC601 \uC2DC validate or none)
spring.jpa.hibernate.ddl-auto=update
# SQL \uB85C\uADF8 \uD3EC\uB9F7\uD305(\uAC00\uB3C5\uC131)
spring.jpa.properties.hibernate.format_sql=true
# \uC2E4\uC81C\uB85C \uC2E4\uD589\uB418\uB294 SQL \uB85C\uADF8 \uCD9C\uB825(\uC6B4\uC601 \uC2DC\uC5D4 false)
spring.jpa.show-sql=true

# \uCD08\uAE30 sql \uB370\uC774\uD130 \uB85C\uB529
spring.sql.init.mode=never

# Hibernate Batch Insert \uCD5C\uC801\uD654
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false

